const Client = require('../models/Client');
const User = require('../models/User');
const crypto = require('crypto');
const { validationResult } = require('express-validator');

/**
 * @desc      Creates a new client instance (tenant) with its configuration and initial admin user.
 * A unique tenantId is manually generated by incrementing the last one.
 * @route     POST /api/provision/client
 * @access    Private (Super Admin Only)
 */
exports.provisionNewClient = async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.status(400).json({ errors: errors.array() });
    }

    const {
        clientName,
        adminEmail,
        adminPassword,
        cloudinaryCloudName,
        cloudinaryApiKey,
        cloudinaryApiSecret,
        nodemailerEmail,
        nodemailerAppPassword
    } = req.body;

    let savedClient = null; // Keep track of the saved client for potential rollback

    try {
        // 1. Check if the client name is already in use.
        const existingClient = await Client.findOne({ name: clientName });
        if (existingClient) {
            return res.status(409).json({ message: `Client name '${clientName}' is already in use.` });
        }

        // 2. Determine the next tenantId.
        const lastClient = await Client.findOne().sort({ tenantId: -1 });
        const nextTenantId = lastClient ? lastClient.tenantId + 1 : 1001;

        // 3. Generate a unique JWT secret for the new client.
        const jwtSecret = crypto.randomBytes(32).toString('hex');

        // 4. Create the new Client document.
        const newClient = new Client({
            tenantId: nextTenantId,
            name: clientName,
            config: {
                jwtSecret,
                cloudinary: {
                    cloud_name: cloudinaryCloudName,
                    api_key: cloudinaryApiKey,
                    api_secret: cloudinaryApiSecret,
                },
                nodemailer: {
                    user: nodemailerEmail,
                    pass: nodemailerAppPassword,
                },
            },
        });
        
        savedClient = await newClient.save();
        const tenantId = savedClient.tenantId;

        // 5. Create the initial administrator user for this new client.
        const adminUser = new User({
            tenantId, // This will now correctly be saved as a Number.
            name: 'Administrator',
            email: adminEmail.toLowerCase(),
            password: adminPassword,
            role: 'admin',
        });

        await adminUser.save();

        res.status(201).json({
            message: 'Client provisioned successfully!',
            client: {
                id: savedClient._id,
                tenantId: savedClient.tenantId,
                name: savedClient.name,
            }
        });

    } catch (error) {
        console.error('Failed to provision new client:', error.message);

        // If client was created but user failed, delete the client to avoid orphaned data.
        if (savedClient) {
            await Client.findByIdAndDelete(savedClient._id);
        }
        
        // Handle potential race condition where two requests try to create a client with the same tenantId.
        if (error.code === 11000) { 
             return res.status(409).json({ message: 'A client with this name or tenant ID was just created. Please try again.' });
        }

        res.status(500).json({ message: 'Server error during client provisioning.' });
    }
};
